### ISSUE TITLE
support lines ?

### ISSUE THREAD

**Issue by heningyuan6256** [123Wampir/CloseUp#10]
Will future versions include rendering the lines of the model onto the canvas and being able to accurately measure the lines

**Comment by dvronin** [comment]
Hi @heningyuan6256! Did you mean something similar to edges, like in [3dviewer.net](https://3dviewer.net/)?
![image](https://github.com/user-attachments/assets/d87576be-b982-4bd5-88ff-164859edca1a)
It is possible and i think there's no problem to implement it.

**Comment by heningyuan6256** [comment]
Can the line be accurately measured, such as the two points selected, or the diameter of the circle directly measured

**Comment by heningyuan6256** [comment]
The mouse can't pick points accurately

**Comment by dvronin** [comment]
Viewer can't apperate on brep data directly. All models you load, will be triangulated and displayed as mesh of polygons. This mean that there's always a some level of approximation to your initial model, which is also mean that we loss all topological info (surfaces, edges, actual points). So there's no way we can accurate measure model dimensions without using some CAD kernel like OCCT. Work arround here is to measure the length of edge loop like the Blender does, but it's still give you a proximate result

**Comment by heningyuan6256** [comment]
Thank you for your replay! I also want to know, If you import step, can you parse topological info through occt-import-js and render it to viewer？

**Comment by dvronin** [comment]
No, occt-import-js produces only triangulated meshes of solids. Viewer then can render it. If you need topological data, something like [Mayo](https://github.com/fougue/mayo) may be suitable for you

**Comment by heningyuan6256** [comment]
thankyou for your suggestion !
